export const DRAFTED = "DRAFTED"; // x
export const PENDING = "PENDING";
export const ACCEPTED = "ACCEPTED";
export const ON_THE_WAY = "ON_THE_WAY";
export const ARRIVED = "ARRIVED";
export const CANCELLED_BY_CLIENT = "CANCELLED_BY_CLIENT"; // x
export const CANCELLED_BY_PROVIDER = "CANCELLED_BY_PROVIDER"; // x
export const IN_PROGRESS = "IN_PROGRESS";
export const PAUSED_BY_CLIENT = "PAUSED_BY_CLIENT";
export const PAUSED_BY_PROVIDER = "PAUSED_BY_PROVIDER";
export const FINISHED_WORK = "FINISHED_WORK";
export const ENDED = "ENDED"; // x
export const REFUSED = "REFUSED"; // x
export const ACCEPTED_BY_PROVIDER = "ACCEPTED_BY_PROVIDER";
export const REJECTED_BY_PROVIDER = "REJECTED_BY_PROVIDER";
export const ACCEPTED_BY_CLIENT = "ACCEPTED_BY_CLIENT";
export const REJECTED_BY_CLIENT = "REJECTED_BY_CLIENT";
export const CANCELED_BY_CLIENT = "CANCELED_BY_CLIENT";
export const FINISHED_WORKING = "FINISHED_WORKING";
export const DELIVERED = "DELIVERED";
export const approved = "approved ";
export const Paid = "Paid";
export const Delivery = "Delivery";
export const Received = "Received";
export const Retrieval = "Retrieval";
export const Retrieved = "Retrieved";
export const PaymentReceived = "PaymentReceived";
export const RequestAPreview = "RequestAPreview";
export const AgreeToThePreview = "AgreeToThePreview";

// export const ENDED = "ENDED";
